version: '3.7'

services:
  db:
    image: mongo
    container_name: seminario-sd-db
    restart: always
    volumes:
      - seminario-sd-db:/data/db
    ports:
      - '27018:27017'
    networks:
      - backend

volumes:
  seminario-sd-db:

networks:
  backend:
    driver: bridge
